/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.ClienteDAO;
import DAO.EntradaDAO;
import DAO.ProdutoDAO;
import DAO.Session;
import DAO.VendaDAO;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Collection;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Cliente;
import model.Entrada;
import model.ItensProdutos;
import model.ItensVenda;
import model.Produto;
import model.Venda;

/**
 *
 * @author Bruno
 */
public class VendaView extends javax.swing.JInternalFrame {

    private Object pnlPrincipal;
    Produto produto;
    ProdutoDAO produtoDAO;
    ItensVenda itemVenda;
    Venda venda;
    ClienteDAO clienteDAO;
    VendaDAO vendaDAO;
    Cliente cliente;

    /**
     * Creates new form EntradaView
     */
    public VendaView() {
        produtoDAO = new ProdutoDAO();
        vendaDAO = new VendaDAO();
        venda = new Venda();
        clienteDAO = new ClienteDAO();
        initComponents();
        this.setVisible(true);
        Session session = Session.getInstance();
        txtVendedor.setText(session.getNome());
        txtVendedor.disable();
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        Date date = new Date();
        txtData.setText(formatter.format(date));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialog_produto = new javax.swing.JDialog();
        txtPesquisarProduto = new javax.swing.JTextField();
        btnAdicionar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jTable = new javax.swing.JScrollPane();
        tbProdutos = new javax.swing.JTable();
        dialog_cliente = new javax.swing.JDialog();
        btnaddSelectFornecedor = new javax.swing.JButton();
        btnCancelarFornecedor = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtPesquisarCliente = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbCliente = new javax.swing.JTable();
        txtValorItem = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtQuantVenda = new javax.swing.JTextField();
        txtCliente = new javax.swing.JTextField();
        txtProduto = new javax.swing.JTextField();
        addProduto = new javax.swing.JButton();
        addCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbItens = new javax.swing.JTable();
        btnaddItem = new javax.swing.JButton();
        btnremoveItem = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        txtData = new javax.swing.JFormattedTextField();
        txtValorTotal = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtVendedor = new javax.swing.JTextField();

        dialog_produto.setMinimumSize(new java.awt.Dimension(720, 314));

        txtPesquisarProduto.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtPesquisarProdutoCaretUpdate(evt);
            }
        });

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        jLabel7.setText("Pesquisar");

        jButton6.setText("Cancelar");

        tbProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Quantidade", "Categoria", "Marca"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable.setViewportView(tbProdutos);

        javax.swing.GroupLayout dialog_produtoLayout = new javax.swing.GroupLayout(dialog_produto.getContentPane());
        dialog_produto.getContentPane().setLayout(dialog_produtoLayout);
        dialog_produtoLayout.setHorizontalGroup(
            dialog_produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_produtoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialog_produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialog_produtoLayout.createSequentialGroup()
                        .addComponent(btnAdicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6))
                    .addComponent(jLabel7)
                    .addComponent(txtPesquisarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialog_produtoLayout.createSequentialGroup()
                .addComponent(jTable, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        dialog_produtoLayout.setVerticalGroup(
            dialog_produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_produtoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(dialog_produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionar)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesquisarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTable, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        dialog_cliente.setMinimumSize(new java.awt.Dimension(720, 315));

        btnaddSelectFornecedor.setText("Adicionar");
        btnaddSelectFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddSelectFornecedorActionPerformed(evt);
            }
        });

        btnCancelarFornecedor.setText("Cancelar");

        jLabel8.setText("Pesquisar");

        txtPesquisarCliente.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtPesquisarClienteCaretUpdate(evt);
            }
        });

        tbCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Telefone", "Celular", "E-mail", "Cidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbClienteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbCliente);

        javax.swing.GroupLayout dialog_clienteLayout = new javax.swing.GroupLayout(dialog_cliente.getContentPane());
        dialog_cliente.getContentPane().setLayout(dialog_clienteLayout);
        dialog_clienteLayout.setHorizontalGroup(
            dialog_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_clienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialog_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPesquisarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dialog_clienteLayout.createSequentialGroup()
                        .addComponent(btnaddSelectFornecedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelarFornecedor))
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
        );
        dialog_clienteLayout.setVerticalGroup(
            dialog_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_clienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(dialog_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnaddSelectFornecedor)
                    .addComponent(btnCancelarFornecedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesquisarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        setClosable(true);
        setTitle("Venda");

        jLabel2.setText("Valor Unitario");

        jLabel3.setText("Data");

        jLabel5.setText("Quantidade");

        addProduto.setText("Adicionar Produto");
        addProduto.setEnabled(false);
        addProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProdutoActionPerformed(evt);
            }
        });

        addCliente.setText("Procurar Cliente");
        addCliente.setEnabled(false);
        addCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClienteActionPerformed(evt);
            }
        });

        tbItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Quantidade ", "Preço", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbItens);

        btnaddItem.setText("+");
        btnaddItem.setEnabled(false);
        btnaddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddItemActionPerformed(evt);
            }
        });

        btnremoveItem.setText("-");
        btnremoveItem.setEnabled(false);
        btnremoveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnremoveItemActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalvar.setText("Confirmar");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        try {
            txtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtData.setEnabled(false);

        txtValorTotal.setText("Valor Total:");

        jLabel10.setText("Vendedor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtValorTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSalvar)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnaddItem)
                                .addGap(18, 18, 18)
                                .addComponent(btnremoveItem)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtProduto))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtQuantVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtValorItem, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(txtCliente))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNovo)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addProduto)
                            .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addCliente))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQuantVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtValorItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnremoveItem)
                    .addComponent(btnaddItem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar)
                    .addComponent(txtValorTotal))
                .addContainerGap(155, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProdutoActionPerformed
        dialog_produto.setVisible(true);
        dialog_produto.setLocationRelativeTo(null);
        try {
            readJTableProduto(txtPesquisarProduto.getText());
        } catch (SQLException ex) {
            Logger.getLogger(VendaView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addProdutoActionPerformed

    private void addClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClienteActionPerformed
        dialog_cliente.setVisible(true);
        dialog_cliente.setLocationRelativeTo(null);
        try {
            readJTableCliente(txtPesquisarCliente.getText());
        } catch (SQLException ex) {
            Logger.getLogger(VendaView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addClienteActionPerformed

    public void readJTableProduto(String nome) throws SQLException {
        DefaultTableModel modelF = (DefaultTableModel) tbProdutos.getModel();
        modelF.setNumRows(0);
        for (Produto p : produtoDAO.readProdutoLikeEstoque(nome)) {
            modelF.addRow(new Object[]{
                p.getIdProduto(),
                p.getNome(),
                p.getQuantidadeEstoque(),
                p.getNomeCategoria(),
                p.getNomeMarca()
            });

        }
    }

    public Double updateTotal() {
        double total = 0;
        for (ItensVenda i : venda.getItensVenda()) {
            total += (double) i.getPrecoUnitario() * (double) i.getQuantidade();
        }
        return total;
    }

    public void readJTableCliente(String nome) throws SQLException {
        DefaultTableModel modelF = (DefaultTableModel) tbCliente.getModel();
        modelF.setNumRows(0);
        for (Cliente c : clienteDAO.readCliente(nome)) {
            modelF.addRow(new Object[]{
                c.getIdCliente(),
                c.getNome(),
                c.getTelefone(),
                c.getCelular(),
                c.getEmail(),
                c.getCidade()
            });

        }
    }

    public void readTabelaItens() throws SQLException {
        DefaultTableModel modelItens = (DefaultTableModel) tbItens.getModel();
        modelItens.setNumRows(0);
        for (ItensVenda i : venda.getItensVenda()) {
            modelItens.addRow(new Object[]{
                i.getProduto().getNome(),
                i.getQuantidade(),
                i.getPrecoUnitario(),
                i.getPrecoUnitario() * i.getQuantidade()
            });
        }
    }


    private void txtPesquisarProdutoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtPesquisarProdutoCaretUpdate
        try {
            readJTableProduto(txtPesquisarProduto.getText());
        } catch (SQLException ex) {
            Logger.getLogger(VendaView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtPesquisarProdutoCaretUpdate

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        if (tbProdutos.getSelectedRow() != -1) {
            try {
                produto = produtoDAO.BuscarProduto(tbProdutos.getValueAt(tbProdutos.getSelectedRow(), 0).toString());
            } catch (SQLException ex) {
                Logger.getLogger(VendaView.class.getName()).log(Level.SEVERE, null, ex);
            }
            txtProduto.setText(produto.getNome());
            txtValorItem.setText(String.valueOf(produto.getValorSaida()));
            txtProduto.disable();
            dialog_produto.dispose();
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void tbClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbClienteMouseClicked

    }//GEN-LAST:event_tbClienteMouseClicked

    private void btnaddSelectFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddSelectFornecedorActionPerformed
        if (tbCliente.getSelectedRow() != -1) {
            try {
                cliente = clienteDAO.BuscarCliente(tbCliente.getValueAt(tbCliente.getSelectedRow(), 0).toString());
            } catch (SQLException ex) {
                Logger.getLogger(VendaView.class.getName()).log(Level.SEVERE, null, ex);
            }
            txtCliente.setText(cliente.getNome());
            txtCliente.disable();
            dialog_cliente.dispose();
        }
    }//GEN-LAST:event_btnaddSelectFornecedorActionPerformed

    private void btnaddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddItemActionPerformed
        if (txtProduto.getText().isEmpty() || txtValorItem.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha os campos vazios!!");
        } else {
            if (Integer.parseInt(txtQuantVenda.getText()) <= produto.getQuantidadeEstoque()) {
                itemVenda = new ItensVenda();
                itemVenda.setProduto(produto);
                itemVenda.setPrecoUnitario(Float.valueOf(txtValorItem.getText()));
                itemVenda.setQuantidade(Integer.valueOf(txtQuantVenda.getText()));
                venda.getItensVenda().add(itemVenda);
                txtData.disable();
                txtValorTotal.disable();
                btnaddSelectFornecedor.disable();
                addCliente.setEnabled(false);
                txtProduto.setText("");
                txtProduto.enable();
                txtQuantVenda.setText("");
                txtValorItem.setText("");
                try {
                    readTabelaItens();
                } catch (SQLException ex) {
                    Logger.getLogger(VendaView.class.getName()).log(Level.SEVERE, null, ex);
                }
                preparaAdd();
                txtValorTotal.setText("Valor Total: " + String.valueOf(updateTotal()));
            }else{
                txtQuantVenda.setText(String.valueOf(produto.getQuantidadeEstoque()));
                JOptionPane.showMessageDialog(null, "Verifique a quantidade, estoque menor que o informado!");
            }
        }
    }//GEN-LAST:event_btnaddItemActionPerformed

    private void btnremoveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnremoveItemActionPerformed
        if (tbItens.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um item da tabela");
        } else {
            venda.getItensVenda().remove(tbItens.getSelectedRow());
            try {
                readTabelaItens();
            } catch (SQLException ex) {
                Logger.getLogger(VendaView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnremoveItemActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (txtVendedor.getText().isEmpty()) {
            JOptionPane.showConfirmDialog(null, "Adicione um produto na tabela");

        } else {
            int confirma = JOptionPane.showConfirmDialog(null, "Deseja confirmar essa venda?");
            if (confirma == 0) {
                String text1 = txtData.getText();
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                java.util.Date textFieldAsDate1 = null;
                try {
                    textFieldAsDate1 = sdf.parse(text1);
                } catch (ParseException ex) {
                    Logger.getLogger(VendaView.class.getName()).log(Level.SEVERE, null, ex);
                }
                venda.setDataVenda(textFieldAsDate1);
                venda.setIdFunc(Session.getInstance().getIdFuncionario());
                venda.setValorTotal(updateTotal());
                venda.setCli(cliente);
                try {
                    vendaDAO.salvarVenda(venda);
                } catch (SQLException ex) {
                    Logger.getLogger(VendaView.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(null, "Venda cadastrada com sucesso!");
                desabilita();
                limpaTb();
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        preparaNovo();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        int confirma = JOptionPane.showConfirmDialog(null, "Deseja cancelar essa entrada? todos os dados serão apagados");
        if (confirma == 0) {
            desabilita();
            limpaTb();
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtPesquisarClienteCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtPesquisarClienteCaretUpdate
        try {
            readJTableCliente(txtPesquisarCliente.getText());
        } catch (SQLException ex) {
            Logger.getLogger(VendaView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtPesquisarClienteCaretUpdate

    public void updateQuantity() {
        txtQuantVenda.setText("");
    }

    public boolean isNumeric(String strNum) {
        if (strNum == null) {
            return false;
        }
        try {
            double d = Double.parseDouble(strNum);
        } catch (NumberFormatException nfe) {
            return false;
        }
        return true;
    }

    public void preparaNovo() {
        txtValorTotal.setEnabled(true);
        btnSalvar.setEnabled(false);
        btnCancelar.setEnabled(true);
        btnNovo.setEnabled(false);
        btnaddItem.setEnabled(true);
        btnremoveItem.setEnabled(true);
        txtCliente.setEnabled(true);
        addProduto.setEnabled(true);
        addCliente.setEnabled(true);
        txtCliente.setText("");
        txtProduto.setText("");
        txtQuantVenda.setText("");
        txtValorTotal.setText("");
        txtValorItem.setText("");
    }

    public void preparaAdd() {
        btnSalvar.setEnabled(true);
    }

    public void desabilita() {
        txtValorTotal.setEnabled(false);
        btnSalvar.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnNovo.setEnabled(true);
        btnaddItem.setEnabled(false);
        btnremoveItem.setEnabled(false);
        addProduto.setEnabled(false);
        addCliente.setEnabled(false);
        txtCliente.setText("");
        txtProduto.setText("");
        txtQuantVenda.setText("");
        txtValorTotal.setText("");
        txtValorItem.setText("");
        txtCliente.setEnabled(false);

    }

    public void limpaTb() {
        DefaultTableModel dm = (DefaultTableModel) tbItens.getModel();
        while (dm.getRowCount() > 0) {
            dm.removeRow(0);
            venda.getItensVenda().clear();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCliente;
    private javax.swing.JButton addProduto;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelarFornecedor;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnaddItem;
    private javax.swing.JButton btnaddSelectFornecedor;
    private javax.swing.JButton btnremoveItem;
    private javax.swing.JDialog dialog_cliente;
    private javax.swing.JDialog dialog_produto;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jTable;
    private javax.swing.JTable tbCliente;
    private javax.swing.JTable tbItens;
    private javax.swing.JTable tbProdutos;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JTextField txtPesquisarCliente;
    private javax.swing.JTextField txtPesquisarProduto;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtQuantVenda;
    private javax.swing.JTextField txtValorItem;
    private javax.swing.JLabel txtValorTotal;
    private javax.swing.JTextField txtVendedor;
    // End of variables declaration//GEN-END:variables

}
